[package]
name = "algorithm-w"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
lalrpop-util = { version = "0.22.2", features = ["lexer", "unicode"] }
thiserror = "2.0.17"

[build-dependencies]
lalrpop = "0.22.2"
